name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Lockfile may be out of sync; fall back to install.
      - name: Install deps
        run: |
          npm ci || npm install --no-audit --no-fund

      # Add script deps without changing your repo
      - name: Install converter deps (xlsx)
        run: npm install --no-save xlsx

      # Convert Excel -> GeoJSON before building the site
      - name: Generate retailers.geojson from data/partners.xlsx
        env:
          MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
          NEXT_PUBLIC_MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
        run: |
          node -e "console.log('Token length:', (process.env.NEXT_PUBLIC_MAPBOX_PUBLIC_TOKEN||'').length)"
          node scripts/partners-to-geojson.mjs
          ls -la public/data || true
          test -f public/data/retailers.geojson || (echo 'Missing retailers.geojson' && exit 1)

      - name: Build (Next.js static export)
        env:
          NEXT_PUBLIC_MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
          NEXT_PUBLIC_REPO_NAME: ${{ secrets.REPO_NAME }}
          MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: |
          npm run build
          # fallback export if Next didn't output ./out (shouldn't be needed)
          if [ ! -d "./out" ]; then
            npx --yes next export
          fi
          echo "--- out/ contents ---"
          ls -la out || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
