name: Update GeoJSON

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-geojson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas geopy openpyxl

      - name: Run build_geojson.py
        env:
          MAPBOX_PUBLIC_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_PUBLIC_TOKEN }}
        run: python scripts/build_geojson.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/retailers.geojson public/data/geocode-cache.json
          git commit -m "ci: update GeoJSON data" || echo "No changes to commit"
          git push
